'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace PagibigWebService
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ServiceSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Service
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GetMemberInfoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetMemberMCRecordOperationCompleted As System.Threading.SendOrPostCallback
        
        Private PushCardInfoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateCardInfoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ActiveCardInfoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.ACC_MS_WEBSERVICE.My.MySettings.Default.ACC_MS_WEBSERVICE_PagibigWebService_Service
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetMemberInfoCompleted As GetMemberInfoCompletedEventHandler
        
        '''<remarks/>
        Public Event GetMemberMCRecordCompleted As GetMemberMCRecordCompletedEventHandler
        
        '''<remarks/>
        Public Event PushCardInfoCompleted As PushCardInfoCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateCardInfoCompleted As UpdateCardInfoCompletedEventHandler
        
        '''<remarks/>
        Public Event ActiveCardInfoCompleted As ActiveCardInfoCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMemberInfo", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetMemberInfo(ByVal UID As String, ByVal PWD As String, ByVal MEMBERID As String) As SearchResult
            Dim results() As Object = Me.Invoke("GetMemberInfo", New Object() {UID, PWD, MEMBERID})
            Return CType(results(0),SearchResult)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetMemberInfoAsync(ByVal UID As String, ByVal PWD As String, ByVal MEMBERID As String)
            Me.GetMemberInfoAsync(UID, PWD, MEMBERID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetMemberInfoAsync(ByVal UID As String, ByVal PWD As String, ByVal MEMBERID As String, ByVal userState As Object)
            If (Me.GetMemberInfoOperationCompleted Is Nothing) Then
                Me.GetMemberInfoOperationCompleted = AddressOf Me.OnGetMemberInfoOperationCompleted
            End If
            Me.InvokeAsync("GetMemberInfo", New Object() {UID, PWD, MEMBERID}, Me.GetMemberInfoOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetMemberInfoOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetMemberInfoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetMemberInfoCompleted(Me, New GetMemberInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMemberMCRecord", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetMemberMCRecord(ByVal UID As String, ByVal PWD As String, ByVal PagIBIGID As String) As Result_MemberMCRec
            Dim results() As Object = Me.Invoke("GetMemberMCRecord", New Object() {UID, PWD, PagIBIGID})
            Return CType(results(0),Result_MemberMCRec)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetMemberMCRecordAsync(ByVal UID As String, ByVal PWD As String, ByVal PagIBIGID As String)
            Me.GetMemberMCRecordAsync(UID, PWD, PagIBIGID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetMemberMCRecordAsync(ByVal UID As String, ByVal PWD As String, ByVal PagIBIGID As String, ByVal userState As Object)
            If (Me.GetMemberMCRecordOperationCompleted Is Nothing) Then
                Me.GetMemberMCRecordOperationCompleted = AddressOf Me.OnGetMemberMCRecordOperationCompleted
            End If
            Me.InvokeAsync("GetMemberMCRecord", New Object() {UID, PWD, PagIBIGID}, Me.GetMemberMCRecordOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetMemberMCRecordOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetMemberMCRecordCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetMemberMCRecordCompleted(Me, New GetMemberMCRecordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PushCardInfo", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PushCardInfo(ByVal userid As String, ByVal user_password As String, ByVal pagibigid As String, ByVal lname As String, ByVal fname As String, ByVal mname As String, ByVal birthdate As String, ByVal mobileno As String, ByVal cardno As String, ByVal accountno As String, ByVal expiry_date As String, ByVal date_issued As String, ByVal bank_code As String, ByVal msb_code As String) As ExecuteResult
            Dim results() As Object = Me.Invoke("PushCardInfo", New Object() {userid, user_password, pagibigid, lname, fname, mname, birthdate, mobileno, cardno, accountno, expiry_date, date_issued, bank_code, msb_code})
            Return CType(results(0),ExecuteResult)
        End Function
        
        '''<remarks/>
        Public Overloads Sub PushCardInfoAsync(ByVal userid As String, ByVal user_password As String, ByVal pagibigid As String, ByVal lname As String, ByVal fname As String, ByVal mname As String, ByVal birthdate As String, ByVal mobileno As String, ByVal cardno As String, ByVal accountno As String, ByVal expiry_date As String, ByVal date_issued As String, ByVal bank_code As String, ByVal msb_code As String)
            Me.PushCardInfoAsync(userid, user_password, pagibigid, lname, fname, mname, birthdate, mobileno, cardno, accountno, expiry_date, date_issued, bank_code, msb_code, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PushCardInfoAsync(ByVal userid As String, ByVal user_password As String, ByVal pagibigid As String, ByVal lname As String, ByVal fname As String, ByVal mname As String, ByVal birthdate As String, ByVal mobileno As String, ByVal cardno As String, ByVal accountno As String, ByVal expiry_date As String, ByVal date_issued As String, ByVal bank_code As String, ByVal msb_code As String, ByVal userState As Object)
            If (Me.PushCardInfoOperationCompleted Is Nothing) Then
                Me.PushCardInfoOperationCompleted = AddressOf Me.OnPushCardInfoOperationCompleted
            End If
            Me.InvokeAsync("PushCardInfo", New Object() {userid, user_password, pagibigid, lname, fname, mname, birthdate, mobileno, cardno, accountno, expiry_date, date_issued, bank_code, msb_code}, Me.PushCardInfoOperationCompleted, userState)
        End Sub
        
        Private Sub OnPushCardInfoOperationCompleted(ByVal arg As Object)
            If (Not (Me.PushCardInfoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PushCardInfoCompleted(Me, New PushCardInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateCardInfo", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UpdateCardInfo(ByVal userid As String, ByVal user_password As String, ByVal pagibigid As String, ByVal old_cardno As String, ByVal new_cardno As String, ByVal accountno As String, ByVal bank_code As String) As ExecuteResult
            Dim results() As Object = Me.Invoke("UpdateCardInfo", New Object() {userid, user_password, pagibigid, old_cardno, new_cardno, accountno, bank_code})
            Return CType(results(0),ExecuteResult)
        End Function
        
        '''<remarks/>
        Public Overloads Sub UpdateCardInfoAsync(ByVal userid As String, ByVal user_password As String, ByVal pagibigid As String, ByVal old_cardno As String, ByVal new_cardno As String, ByVal accountno As String, ByVal bank_code As String)
            Me.UpdateCardInfoAsync(userid, user_password, pagibigid, old_cardno, new_cardno, accountno, bank_code, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateCardInfoAsync(ByVal userid As String, ByVal user_password As String, ByVal pagibigid As String, ByVal old_cardno As String, ByVal new_cardno As String, ByVal accountno As String, ByVal bank_code As String, ByVal userState As Object)
            If (Me.UpdateCardInfoOperationCompleted Is Nothing) Then
                Me.UpdateCardInfoOperationCompleted = AddressOf Me.OnUpdateCardInfoOperationCompleted
            End If
            Me.InvokeAsync("UpdateCardInfo", New Object() {userid, user_password, pagibigid, old_cardno, new_cardno, accountno, bank_code}, Me.UpdateCardInfoOperationCompleted, userState)
        End Sub
        
        Private Sub OnUpdateCardInfoOperationCompleted(ByVal arg As Object)
            If (Not (Me.UpdateCardInfoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UpdateCardInfoCompleted(Me, New UpdateCardInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActiveCardInfo", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ActiveCardInfo(ByVal userid As String, ByVal user_password As String, ByVal pagibigid As String, ByVal bank_code As String) As Card_ExecuteResult
            Dim results() As Object = Me.Invoke("ActiveCardInfo", New Object() {userid, user_password, pagibigid, bank_code})
            Return CType(results(0),Card_ExecuteResult)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ActiveCardInfoAsync(ByVal userid As String, ByVal user_password As String, ByVal pagibigid As String, ByVal bank_code As String)
            Me.ActiveCardInfoAsync(userid, user_password, pagibigid, bank_code, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ActiveCardInfoAsync(ByVal userid As String, ByVal user_password As String, ByVal pagibigid As String, ByVal bank_code As String, ByVal userState As Object)
            If (Me.ActiveCardInfoOperationCompleted Is Nothing) Then
                Me.ActiveCardInfoOperationCompleted = AddressOf Me.OnActiveCardInfoOperationCompleted
            End If
            Me.InvokeAsync("ActiveCardInfo", New Object() {userid, user_password, pagibigid, bank_code}, Me.ActiveCardInfoOperationCompleted, userState)
        End Sub
        
        Private Sub OnActiveCardInfoOperationCompleted(ByVal arg As Object)
            If (Not (Me.ActiveCardInfoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ActiveCardInfoCompleted(Me, New ActiveCardInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SearchResult
        
        Private isGetField As Boolean
        
        Private memberInfoField As HDMFMember
        
        Private isCompleteField As Boolean
        
        Private getErrorMsgField As String
        
        '''<remarks/>
        Public Property IsGet() As Boolean
            Get
                Return Me.isGetField
            End Get
            Set
                Me.isGetField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MemberInfo() As HDMFMember
            Get
                Return Me.memberInfoField
            End Get
            Set
                Me.memberInfoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsComplete() As Boolean
            Get
                Return Me.isCompleteField
            End Get
            Set
                Me.isCompleteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property GetErrorMsg() As String
            Get
                Return Me.getErrorMsgField
            End Get
            Set
                Me.getErrorMsgField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class HDMFMember
        
        Private pagIBIGIDNoField As String
        
        Private rTNField As String
        
        Private memberNameField As HDMFName
        
        Private motherNameField As HDMFName
        
        Private fatherNameField As HDMFName
        
        Private spouseNameField As HDMFName
        
        Private dateOfBirthField As String
        
        Private placeOfBirthField As String
        
        Private countryOfBirthField As String
        
        Private cityMunicipalityOfBirthField As String
        
        Private genderField As String
        
        Private civilStatusField As String
        
        Private citizenshipField As HDMFDescCode
        
        Private emailAddressField As String
        
        Private commonRefNoField As String
        
        Private sSSIDNoField As String
        
        Private gSISIDNoField As String
        
        Private tINField As String
        
        Private memberCategoryInfoField As HDMFMembershipCategory
        
        Private permanentAddressField As HDMFAddress
        
        Private presentAddressField As HDMFAddress
        
        Private preferredMailingAddressField As String
        
        Private homeTelNoField As HDMFContactInfo
        
        Private mobileTelNoField As HDMFContactInfo
        
        Private businessDirectTelNoField As HDMFContactInfo
        
        Private businessTrunkTelNoField As HDMFContactInfo
        
        Private employmentHistoryField() As HDMFEmploymentHistory
        
        '''<remarks/>
        Public Property PagIBIGIDNo() As String
            Get
                Return Me.pagIBIGIDNoField
            End Get
            Set
                Me.pagIBIGIDNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RTN() As String
            Get
                Return Me.rTNField
            End Get
            Set
                Me.rTNField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MemberName() As HDMFName
            Get
                Return Me.memberNameField
            End Get
            Set
                Me.memberNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MotherName() As HDMFName
            Get
                Return Me.motherNameField
            End Get
            Set
                Me.motherNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FatherName() As HDMFName
            Get
                Return Me.fatherNameField
            End Get
            Set
                Me.fatherNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SpouseName() As HDMFName
            Get
                Return Me.spouseNameField
            End Get
            Set
                Me.spouseNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DateOfBirth() As String
            Get
                Return Me.dateOfBirthField
            End Get
            Set
                Me.dateOfBirthField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PlaceOfBirth() As String
            Get
                Return Me.placeOfBirthField
            End Get
            Set
                Me.placeOfBirthField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CountryOfBirth() As String
            Get
                Return Me.countryOfBirthField
            End Get
            Set
                Me.countryOfBirthField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CityMunicipalityOfBirth() As String
            Get
                Return Me.cityMunicipalityOfBirthField
            End Get
            Set
                Me.cityMunicipalityOfBirthField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Gender() As String
            Get
                Return Me.genderField
            End Get
            Set
                Me.genderField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CivilStatus() As String
            Get
                Return Me.civilStatusField
            End Get
            Set
                Me.civilStatusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Citizenship() As HDMFDescCode
            Get
                Return Me.citizenshipField
            End Get
            Set
                Me.citizenshipField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EmailAddress() As String
            Get
                Return Me.emailAddressField
            End Get
            Set
                Me.emailAddressField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CommonRefNo() As String
            Get
                Return Me.commonRefNoField
            End Get
            Set
                Me.commonRefNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SSSIDNo() As String
            Get
                Return Me.sSSIDNoField
            End Get
            Set
                Me.sSSIDNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property GSISIDNo() As String
            Get
                Return Me.gSISIDNoField
            End Get
            Set
                Me.gSISIDNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TIN() As String
            Get
                Return Me.tINField
            End Get
            Set
                Me.tINField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MemberCategoryInfo() As HDMFMembershipCategory
            Get
                Return Me.memberCategoryInfoField
            End Get
            Set
                Me.memberCategoryInfoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PermanentAddress() As HDMFAddress
            Get
                Return Me.permanentAddressField
            End Get
            Set
                Me.permanentAddressField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PresentAddress() As HDMFAddress
            Get
                Return Me.presentAddressField
            End Get
            Set
                Me.presentAddressField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PreferredMailingAddress() As String
            Get
                Return Me.preferredMailingAddressField
            End Get
            Set
                Me.preferredMailingAddressField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property HomeTelNo() As HDMFContactInfo
            Get
                Return Me.homeTelNoField
            End Get
            Set
                Me.homeTelNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MobileTelNo() As HDMFContactInfo
            Get
                Return Me.mobileTelNoField
            End Get
            Set
                Me.mobileTelNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BusinessDirectTelNo() As HDMFContactInfo
            Get
                Return Me.businessDirectTelNoField
            End Get
            Set
                Me.businessDirectTelNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BusinessTrunkTelNo() As HDMFContactInfo
            Get
                Return Me.businessTrunkTelNoField
            End Get
            Set
                Me.businessTrunkTelNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EmploymentHistory() As HDMFEmploymentHistory()
            Get
                Return Me.employmentHistoryField
            End Get
            Set
                Me.employmentHistoryField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class HDMFName
        
        Private lastNameField As String
        
        Private firstNameField As String
        
        Private middleNameField As String
        
        Private nameExtensionField As String
        
        Private noMiddleNameField As Boolean
        
        '''<remarks/>
        Public Property LastName() As String
            Get
                Return Me.lastNameField
            End Get
            Set
                Me.lastNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FirstName() As String
            Get
                Return Me.firstNameField
            End Get
            Set
                Me.firstNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MiddleName() As String
            Get
                Return Me.middleNameField
            End Get
            Set
                Me.middleNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NameExtension() As String
            Get
                Return Me.nameExtensionField
            End Get
            Set
                Me.nameExtensionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NoMiddleName() As Boolean
            Get
                Return Me.noMiddleNameField
            End Get
            Set
                Me.noMiddleNameField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Card_ExecuteResult
        
        Private cardNumberField As String
        
        Private isGetField As Boolean
        
        Private requestErrorField As String
        
        '''<remarks/>
        Public Property CardNumber() As String
            Get
                Return Me.cardNumberField
            End Get
            Set
                Me.cardNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsGet() As Boolean
            Get
                Return Me.isGetField
            End Get
            Set
                Me.isGetField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RequestError() As String
            Get
                Return Me.requestErrorField
            End Get
            Set
                Me.requestErrorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ExecuteResult
        
        Private is_successField As Boolean
        
        Private getErrorMsgField As String
        
        '''<remarks/>
        Public Property Is_success() As Boolean
            Get
                Return Me.is_successField
            End Get
            Set
                Me.is_successField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property GetErrorMsg() As String
            Get
                Return Me.getErrorMsgField
            End Get
            Set
                Me.getErrorMsgField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class HDMFMCRecord
        
        Private pagIbigIDField As String
        
        Private ingresIDField As String
        
        Private memberLastNameField As String
        
        Private memberFirstNameField As String
        
        Private memberMiddleNameField As String
        
        Private memberNameExtensionField As String
        
        Private dateOfBirthField As String
        
        Private initialPFRNumberField As String
        
        Private initialPFRDateField As String
        
        Private initialPFRAmtField As String
        
        Private lastPeriodCoverField As String
        
        Private lastPFRNumberField As String
        
        Private lastPFRDateField As String
        
        Private lastPFRAmtField As String
        
        Private tAVBalanceField As String
        
        Private branchField As String
        
        Private employerNameField As String
        
        Private statusField As String
        
        '''<remarks/>
        Public Property PagIbigID() As String
            Get
                Return Me.pagIbigIDField
            End Get
            Set
                Me.pagIbigIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IngresID() As String
            Get
                Return Me.ingresIDField
            End Get
            Set
                Me.ingresIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MemberLastName() As String
            Get
                Return Me.memberLastNameField
            End Get
            Set
                Me.memberLastNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MemberFirstName() As String
            Get
                Return Me.memberFirstNameField
            End Get
            Set
                Me.memberFirstNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MemberMiddleName() As String
            Get
                Return Me.memberMiddleNameField
            End Get
            Set
                Me.memberMiddleNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MemberNameExtension() As String
            Get
                Return Me.memberNameExtensionField
            End Get
            Set
                Me.memberNameExtensionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DateOfBirth() As String
            Get
                Return Me.dateOfBirthField
            End Get
            Set
                Me.dateOfBirthField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InitialPFRNumber() As String
            Get
                Return Me.initialPFRNumberField
            End Get
            Set
                Me.initialPFRNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InitialPFRDate() As String
            Get
                Return Me.initialPFRDateField
            End Get
            Set
                Me.initialPFRDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InitialPFRAmt() As String
            Get
                Return Me.initialPFRAmtField
            End Get
            Set
                Me.initialPFRAmtField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LastPeriodCover() As String
            Get
                Return Me.lastPeriodCoverField
            End Get
            Set
                Me.lastPeriodCoverField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LastPFRNumber() As String
            Get
                Return Me.lastPFRNumberField
            End Get
            Set
                Me.lastPFRNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LastPFRDate() As String
            Get
                Return Me.lastPFRDateField
            End Get
            Set
                Me.lastPFRDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LastPFRAmt() As String
            Get
                Return Me.lastPFRAmtField
            End Get
            Set
                Me.lastPFRAmtField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TAVBalance() As String
            Get
                Return Me.tAVBalanceField
            End Get
            Set
                Me.tAVBalanceField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Branch() As String
            Get
                Return Me.branchField
            End Get
            Set
                Me.branchField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EmployerName() As String
            Get
                Return Me.employerNameField
            End Get
            Set
                Me.employerNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Result_MemberMCRec
        
        Private memberMcRecField() As HDMFMCRecord
        
        Private isGetField As Boolean
        
        Private getErrorMsgField As String
        
        '''<remarks/>
        Public Property MemberMcRec() As HDMFMCRecord()
            Get
                Return Me.memberMcRecField
            End Get
            Set
                Me.memberMcRecField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsGet() As Boolean
            Get
                Return Me.isGetField
            End Get
            Set
                Me.isGetField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property GetErrorMsg() As String
            Get
                Return Me.getErrorMsgField
            End Get
            Set
                Me.getErrorMsgField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class HDMFEmploymentHistory
        
        Private employerNameField As String
        
        Private employerAddressField As String
        
        Private dateEmployedField As String
        
        Private dateSeparatedField As String
        
        '''<remarks/>
        Public Property EmployerName() As String
            Get
                Return Me.employerNameField
            End Get
            Set
                Me.employerNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EmployerAddress() As String
            Get
                Return Me.employerAddressField
            End Get
            Set
                Me.employerAddressField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DateEmployed() As String
            Get
                Return Me.dateEmployedField
            End Get
            Set
                Me.dateEmployedField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DateSeparated() As String
            Get
                Return Me.dateSeparatedField
            End Get
            Set
                Me.dateSeparatedField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class HDMFContactInfo
        
        Private country_CodeField As String
        
        Private area_CodeField As String
        
        Private tel_NoField As String
        
        Private local_NoField As String
        
        '''<remarks/>
        Public Property Country_Code() As String
            Get
                Return Me.country_CodeField
            End Get
            Set
                Me.country_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Area_Code() As String
            Get
                Return Me.area_CodeField
            End Get
            Set
                Me.area_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Tel_No() As String
            Get
                Return Me.tel_NoField
            End Get
            Set
                Me.tel_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Local_No() As String
            Get
                Return Me.local_NoField
            End Get
            Set
                Me.local_NoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class HDMFAddress
        
        Private hBURNumberField As String
        
        Private buildingField As String
        
        Private lot_NoField As String
        
        Private block_NoField As String
        
        Private phase_NoField As String
        
        Private house_NoField As String
        
        Private streetNameField As String
        
        Private subdivisionField As String
        
        Private baranggayField As String
        
        Private cityMunicipalityField As String
        
        Private provinceField As String
        
        Private regionField As String
        
        Private zIP_CodeField As String
        
        '''<remarks/>
        Public Property HBURNumber() As String
            Get
                Return Me.hBURNumberField
            End Get
            Set
                Me.hBURNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Building() As String
            Get
                Return Me.buildingField
            End Get
            Set
                Me.buildingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Lot_No() As String
            Get
                Return Me.lot_NoField
            End Get
            Set
                Me.lot_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Block_No() As String
            Get
                Return Me.block_NoField
            End Get
            Set
                Me.block_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Phase_No() As String
            Get
                Return Me.phase_NoField
            End Get
            Set
                Me.phase_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property House_No() As String
            Get
                Return Me.house_NoField
            End Get
            Set
                Me.house_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StreetName() As String
            Get
                Return Me.streetNameField
            End Get
            Set
                Me.streetNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Subdivision() As String
            Get
                Return Me.subdivisionField
            End Get
            Set
                Me.subdivisionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Baranggay() As String
            Get
                Return Me.baranggayField
            End Get
            Set
                Me.baranggayField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CityMunicipality() As String
            Get
                Return Me.cityMunicipalityField
            End Get
            Set
                Me.cityMunicipalityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Province() As String
            Get
                Return Me.provinceField
            End Get
            Set
                Me.provinceField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Region() As String
            Get
                Return Me.regionField
            End Get
            Set
                Me.regionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ZIP_Code() As String
            Get
                Return Me.zIP_CodeField
            End Get
            Set
                Me.zIP_CodeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class HDMFMembershipCategory
        
        Private membershipCategoryField As String
        
        Private employerNameField As String
        
        Private employerAddressField As HDMFAddress
        
        Private employeeIDField As String
        
        Private dateEmployedField As String
        
        Private employmentStatusField As String
        
        Private occupationField As HDMFDescCode
        
        Private aFPSerialBadgeNoField As String
        
        Private depEdDivCodeStnCodeField As String
        
        Private typeOfWorkField As String
        
        Private manningAgencyField As String
        
        Private countryofAssignmentField As String
        
        Private basicSalaryField As String
        
        Private allowanceField As String
        
        '''<remarks/>
        Public Property MembershipCategory() As String
            Get
                Return Me.membershipCategoryField
            End Get
            Set
                Me.membershipCategoryField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EmployerName() As String
            Get
                Return Me.employerNameField
            End Get
            Set
                Me.employerNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EmployerAddress() As HDMFAddress
            Get
                Return Me.employerAddressField
            End Get
            Set
                Me.employerAddressField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EmployeeID() As String
            Get
                Return Me.employeeIDField
            End Get
            Set
                Me.employeeIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DateEmployed() As String
            Get
                Return Me.dateEmployedField
            End Get
            Set
                Me.dateEmployedField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EmploymentStatus() As String
            Get
                Return Me.employmentStatusField
            End Get
            Set
                Me.employmentStatusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Occupation() As HDMFDescCode
            Get
                Return Me.occupationField
            End Get
            Set
                Me.occupationField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AFPSerialBadgeNo() As String
            Get
                Return Me.aFPSerialBadgeNoField
            End Get
            Set
                Me.aFPSerialBadgeNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DepEdDivCodeStnCode() As String
            Get
                Return Me.depEdDivCodeStnCodeField
            End Get
            Set
                Me.depEdDivCodeStnCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TypeOfWork() As String
            Get
                Return Me.typeOfWorkField
            End Get
            Set
                Me.typeOfWorkField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ManningAgency() As String
            Get
                Return Me.manningAgencyField
            End Get
            Set
                Me.manningAgencyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CountryofAssignment() As String
            Get
                Return Me.countryofAssignmentField
            End Get
            Set
                Me.countryofAssignmentField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BasicSalary() As String
            Get
                Return Me.basicSalaryField
            End Get
            Set
                Me.basicSalaryField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Allowance() As String
            Get
                Return Me.allowanceField
            End Get
            Set
                Me.allowanceField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class HDMFDescCode
        
        Private descriptionField As String
        
        Private codeField As String
        
        '''<remarks/>
        Public Property Description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Code() As String
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub GetMemberInfoCompletedEventHandler(ByVal sender As Object, ByVal e As GetMemberInfoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetMemberInfoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As SearchResult
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),SearchResult)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub GetMemberMCRecordCompletedEventHandler(ByVal sender As Object, ByVal e As GetMemberMCRecordCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetMemberMCRecordCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Result_MemberMCRec
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Result_MemberMCRec)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub PushCardInfoCompletedEventHandler(ByVal sender As Object, ByVal e As PushCardInfoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PushCardInfoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ExecuteResult
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ExecuteResult)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub UpdateCardInfoCompletedEventHandler(ByVal sender As Object, ByVal e As UpdateCardInfoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class UpdateCardInfoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ExecuteResult
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ExecuteResult)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub ActiveCardInfoCompletedEventHandler(ByVal sender As Object, ByVal e As ActiveCardInfoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ActiveCardInfoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Card_ExecuteResult
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Card_ExecuteResult)
            End Get
        End Property
    End Class
End Namespace
