'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace MiddleServer
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://allcardtech.com.ph/", ConfigurationName:="MiddleServer.PagIbig_WSSoap")>  _
    Public Interface PagIbig_WSSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://allcardtech.com.ph/is_MID_RTN_Exist", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function is_MID_RTN_Exist(ByVal MID_RTN As String, ByVal webuser As String, ByVal webpass As String) As MiddleServer.SubmitResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://allcardtech.com.ph/Is_Member_Active", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Is_Member_Active(ByVal UID As String, ByVal LN As String, ByVal FN As String, ByVal MN As String) As MiddleServer.ACCMCRecordClassResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://allcardtech.com.ph/is_MemberFullName_Exist", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function is_MemberFullName_Exist(ByVal LName As String, ByVal MName As String, ByVal FName As String, ByVal DOB As Date) As MiddleServer.PrimaryMultiple
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://allcardtech.com.ph/updateRTN", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function updateRTN(ByVal MID As String) As MiddleServer.Result_GetMemberID
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://allcardtech.com.ph/PagIBIGLogIN", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function PagIBIGLogIN(ByVal ApprovedID As String, ByVal ApprovedPW As String, ByVal MID As String) As MiddleServer.Result_AuthenticateMCIFApprover
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://allcardtech.com.ph/")>  _
    Partial Public Class SubmitResult
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private searchResultField As SearchResult
        
        Private memberInfoField As MemberInfo
        
        Private isSentField As Boolean
        
        Private errorMessageField As String
        
        Private successfullyExecutedField As Boolean
        
        Private alreadyExistField As Boolean
        
        Private isSuccessfully_Deleted_to_parkedField As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property SearchResult() As SearchResult
            Get
                Return Me.searchResultField
            End Get
            Set
                Me.searchResultField = value
                Me.RaisePropertyChanged("SearchResult")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property MemberInfo() As MemberInfo
            Get
                Return Me.memberInfoField
            End Get
            Set
                Me.memberInfoField = value
                Me.RaisePropertyChanged("MemberInfo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property IsSent() As Boolean
            Get
                Return Me.isSentField
            End Get
            Set
                Me.isSentField = value
                Me.RaisePropertyChanged("IsSent")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property ErrorMessage() As String
            Get
                Return Me.errorMessageField
            End Get
            Set
                Me.errorMessageField = value
                Me.RaisePropertyChanged("ErrorMessage")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property SuccessfullyExecuted() As Boolean
            Get
                Return Me.successfullyExecutedField
            End Get
            Set
                Me.successfullyExecutedField = value
                Me.RaisePropertyChanged("SuccessfullyExecuted")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property AlreadyExist() As Boolean
            Get
                Return Me.alreadyExistField
            End Get
            Set
                Me.alreadyExistField = value
                Me.RaisePropertyChanged("AlreadyExist")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property IsSuccessfully_Deleted_to_parked() As Boolean
            Get
                Return Me.isSuccessfully_Deleted_to_parkedField
            End Get
            Set
                Me.isSuccessfully_Deleted_to_parkedField = value
                Me.RaisePropertyChanged("IsSuccessfully_Deleted_to_parked")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://allcardtech.com.ph/")>  _
    Partial Public Class SearchResult
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private extensionDataField As ExtensionDataObject
        
        Private isGetField As Boolean
        
        Private memberInfoField As HDMFMember
        
        Private isCompleteField As Boolean
        
        Private getErrorMsgField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property ExtensionData() As ExtensionDataObject
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
                Me.RaisePropertyChanged("ExtensionData")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property IsGet() As Boolean
            Get
                Return Me.isGetField
            End Get
            Set
                Me.isGetField = value
                Me.RaisePropertyChanged("IsGet")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property MemberInfo() As HDMFMember
            Get
                Return Me.memberInfoField
            End Get
            Set
                Me.memberInfoField = value
                Me.RaisePropertyChanged("MemberInfo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property IsComplete() As Boolean
            Get
                Return Me.isCompleteField
            End Get
            Set
                Me.isCompleteField = value
                Me.RaisePropertyChanged("IsComplete")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property GetErrorMsg() As String
            Get
                Return Me.getErrorMsgField
            End Get
            Set
                Me.getErrorMsgField = value
                Me.RaisePropertyChanged("GetErrorMsg")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://allcardtech.com.ph/")>  _
    Partial Public Class ExtensionDataObject
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://allcardtech.com.ph/")>  _
    Partial Public Class Result_AuthenticateMCIFApprover
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private extensionDataField As ExtensionDataObject
        
        Private isSuccessfulField As Boolean
        
        Private errorMessageField As String
        
        Private errorCodeField As String
        
        Private requestDateTimeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property ExtensionData() As ExtensionDataObject
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
                Me.RaisePropertyChanged("ExtensionData")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property IsSuccessful() As Boolean
            Get
                Return Me.isSuccessfulField
            End Get
            Set
                Me.isSuccessfulField = value
                Me.RaisePropertyChanged("IsSuccessful")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property ErrorMessage() As String
            Get
                Return Me.errorMessageField
            End Get
            Set
                Me.errorMessageField = value
                Me.RaisePropertyChanged("ErrorMessage")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property ErrorCode() As String
            Get
                Return Me.errorCodeField
            End Get
            Set
                Me.errorCodeField = value
                Me.RaisePropertyChanged("ErrorCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property RequestDateTime() As String
            Get
                Return Me.requestDateTimeField
            End Get
            Set
                Me.requestDateTimeField = value
                Me.RaisePropertyChanged("RequestDateTime")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://allcardtech.com.ph/")>  _
    Partial Public Class Result_GetMemberID
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private extensionDataField As ExtensionDataObject
        
        Private isGEtField As Boolean
        
        Private pagIBIGIDField As String
        
        Private getErrorMsgField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property ExtensionData() As ExtensionDataObject
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
                Me.RaisePropertyChanged("ExtensionData")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property IsGEt() As Boolean
            Get
                Return Me.isGEtField
            End Get
            Set
                Me.isGEtField = value
                Me.RaisePropertyChanged("IsGEt")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property PagIBIGID() As String
            Get
                Return Me.pagIBIGIDField
            End Get
            Set
                Me.pagIBIGIDField = value
                Me.RaisePropertyChanged("PagIBIGID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property GetErrorMsg() As String
            Get
                Return Me.getErrorMsgField
            End Get
            Set
                Me.getErrorMsgField = value
                Me.RaisePropertyChanged("GetErrorMsg")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://allcardtech.com.ph/")>  _
    Partial Public Class MultipleRecord
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private recMIDField As String
        
        Private recFirstNameField As String
        
        Private recMiddleNameField As String
        
        Private recLastNameField As String
        
        Private recExtField As String
        
        Private recDateOfBirthField As String
        
        Private recMaritalField As String
        
        Private recCitizenshipField As String
        
        Private recSexField As String
        
        Private recBplaceField As String
        
        Private recTinField As String
        
        Private recSSSField As String
        
        Private recEmpNumField As String
        
        Private recPNPField As String
        
        Private recDepEdField As String
        
        Private recMotherMaidenField As String
        
        Private recSpouseField As String
        
        Private recSpouseMiddleNameField As String
        
        Private recSpouseLastNameField As String
        
        Private recSpouseExtField As String
        
        Private recRTNField As String
        
        Private recStatusField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property RecMID() As String
            Get
                Return Me.recMIDField
            End Get
            Set
                Me.recMIDField = value
                Me.RaisePropertyChanged("RecMID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property RecFirstName() As String
            Get
                Return Me.recFirstNameField
            End Get
            Set
                Me.recFirstNameField = value
                Me.RaisePropertyChanged("RecFirstName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property RecMiddleName() As String
            Get
                Return Me.recMiddleNameField
            End Get
            Set
                Me.recMiddleNameField = value
                Me.RaisePropertyChanged("RecMiddleName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property RecLastName() As String
            Get
                Return Me.recLastNameField
            End Get
            Set
                Me.recLastNameField = value
                Me.RaisePropertyChanged("RecLastName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property RecExt() As String
            Get
                Return Me.recExtField
            End Get
            Set
                Me.recExtField = value
                Me.RaisePropertyChanged("RecExt")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property RecDateOfBirth() As String
            Get
                Return Me.recDateOfBirthField
            End Get
            Set
                Me.recDateOfBirthField = value
                Me.RaisePropertyChanged("RecDateOfBirth")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property RecMarital() As String
            Get
                Return Me.recMaritalField
            End Get
            Set
                Me.recMaritalField = value
                Me.RaisePropertyChanged("RecMarital")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property RecCitizenship() As String
            Get
                Return Me.recCitizenshipField
            End Get
            Set
                Me.recCitizenshipField = value
                Me.RaisePropertyChanged("RecCitizenship")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property RecSex() As String
            Get
                Return Me.recSexField
            End Get
            Set
                Me.recSexField = value
                Me.RaisePropertyChanged("RecSex")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property RecBplace() As String
            Get
                Return Me.recBplaceField
            End Get
            Set
                Me.recBplaceField = value
                Me.RaisePropertyChanged("RecBplace")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property RecTin() As String
            Get
                Return Me.recTinField
            End Get
            Set
                Me.recTinField = value
                Me.RaisePropertyChanged("RecTin")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=11)>  _
        Public Property RecSSS() As String
            Get
                Return Me.recSSSField
            End Get
            Set
                Me.recSSSField = value
                Me.RaisePropertyChanged("RecSSS")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=12)>  _
        Public Property RecEmpNum() As String
            Get
                Return Me.recEmpNumField
            End Get
            Set
                Me.recEmpNumField = value
                Me.RaisePropertyChanged("RecEmpNum")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=13)>  _
        Public Property RecPNP() As String
            Get
                Return Me.recPNPField
            End Get
            Set
                Me.recPNPField = value
                Me.RaisePropertyChanged("RecPNP")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=14)>  _
        Public Property RecDepEd() As String
            Get
                Return Me.recDepEdField
            End Get
            Set
                Me.recDepEdField = value
                Me.RaisePropertyChanged("RecDepEd")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=15)>  _
        Public Property RecMotherMaiden() As String
            Get
                Return Me.recMotherMaidenField
            End Get
            Set
                Me.recMotherMaidenField = value
                Me.RaisePropertyChanged("RecMotherMaiden")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=16)>  _
        Public Property RecSpouse() As String
            Get
                Return Me.recSpouseField
            End Get
            Set
                Me.recSpouseField = value
                Me.RaisePropertyChanged("RecSpouse")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=17)>  _
        Public Property RecSpouseMiddleName() As String
            Get
                Return Me.recSpouseMiddleNameField
            End Get
            Set
                Me.recSpouseMiddleNameField = value
                Me.RaisePropertyChanged("RecSpouseMiddleName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=18)>  _
        Public Property RecSpouseLastName() As String
            Get
                Return Me.recSpouseLastNameField
            End Get
            Set
                Me.recSpouseLastNameField = value
                Me.RaisePropertyChanged("RecSpouseLastName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=19)>  _
        Public Property RecSpouseExt() As String
            Get
                Return Me.recSpouseExtField
            End Get
            Set
                Me.recSpouseExtField = value
                Me.RaisePropertyChanged("RecSpouseExt")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=20)>  _
        Public Property RecRTN() As String
            Get
                Return Me.recRTNField
            End Get
            Set
                Me.recRTNField = value
                Me.RaisePropertyChanged("RecRTN")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=21)>  _
        Public Property RecStatus() As String
            Get
                Return Me.recStatusField
            End Get
            Set
                Me.recStatusField = value
                Me.RaisePropertyChanged("RecStatus")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://allcardtech.com.ph/")>  _
    Partial Public Class PrimaryMultiple
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private aCCMCMultipleRecField() As MultipleRecord
        
        Private isSentField As Boolean
        
        Private errorMessageField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Order:=0)>  _
        Public Property ACCMCMultipleRec() As MultipleRecord()
            Get
                Return Me.aCCMCMultipleRecField
            End Get
            Set
                Me.aCCMCMultipleRecField = value
                Me.RaisePropertyChanged("ACCMCMultipleRec")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property IsSent() As Boolean
            Get
                Return Me.isSentField
            End Get
            Set
                Me.isSentField = value
                Me.RaisePropertyChanged("IsSent")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property ErrorMessage() As String
            Get
                Return Me.errorMessageField
            End Get
            Set
                Me.errorMessageField = value
                Me.RaisePropertyChanged("ErrorMessage")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://allcardtech.com.ph/")>  _
    Partial Public Class MemberContribution
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private mCIngresIDField As String
        
        Private mCFirstNameField As String
        
        Private mCMiddleNameField As String
        
        Private mCLastNameField As String
        
        Private mCExtField As String
        
        Private mCDateOfBirthField As String
        
        Private mCInitialPFRNumberField As String
        
        Private mCInitialPFRDateField As String
        
        Private mCInitialPFRAmountField As String
        
        Private mCLastPeriodCoverField As String
        
        Private mCLastPFRDateField As String
        
        Private mCLastPFRNumberField As String
        
        Private mCLastPFRAmountField As String
        
        Private mCTAVBalanceField As String
        
        Private mCEmployerNameField As String
        
        Private mCEmployerBranchField As String
        
        Private mCEmployerStatusField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property MCIngresID() As String
            Get
                Return Me.mCIngresIDField
            End Get
            Set
                Me.mCIngresIDField = value
                Me.RaisePropertyChanged("MCIngresID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property MCFirstName() As String
            Get
                Return Me.mCFirstNameField
            End Get
            Set
                Me.mCFirstNameField = value
                Me.RaisePropertyChanged("MCFirstName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property MCMiddleName() As String
            Get
                Return Me.mCMiddleNameField
            End Get
            Set
                Me.mCMiddleNameField = value
                Me.RaisePropertyChanged("MCMiddleName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property MCLastName() As String
            Get
                Return Me.mCLastNameField
            End Get
            Set
                Me.mCLastNameField = value
                Me.RaisePropertyChanged("MCLastName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property MCExt() As String
            Get
                Return Me.mCExtField
            End Get
            Set
                Me.mCExtField = value
                Me.RaisePropertyChanged("MCExt")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property MCDateOfBirth() As String
            Get
                Return Me.mCDateOfBirthField
            End Get
            Set
                Me.mCDateOfBirthField = value
                Me.RaisePropertyChanged("MCDateOfBirth")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property MCInitialPFRNumber() As String
            Get
                Return Me.mCInitialPFRNumberField
            End Get
            Set
                Me.mCInitialPFRNumberField = value
                Me.RaisePropertyChanged("MCInitialPFRNumber")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property MCInitialPFRDate() As String
            Get
                Return Me.mCInitialPFRDateField
            End Get
            Set
                Me.mCInitialPFRDateField = value
                Me.RaisePropertyChanged("MCInitialPFRDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property MCInitialPFRAmount() As String
            Get
                Return Me.mCInitialPFRAmountField
            End Get
            Set
                Me.mCInitialPFRAmountField = value
                Me.RaisePropertyChanged("MCInitialPFRAmount")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property MCLastPeriodCover() As String
            Get
                Return Me.mCLastPeriodCoverField
            End Get
            Set
                Me.mCLastPeriodCoverField = value
                Me.RaisePropertyChanged("MCLastPeriodCover")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property MCLastPFRDate() As String
            Get
                Return Me.mCLastPFRDateField
            End Get
            Set
                Me.mCLastPFRDateField = value
                Me.RaisePropertyChanged("MCLastPFRDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=11)>  _
        Public Property MCLastPFRNumber() As String
            Get
                Return Me.mCLastPFRNumberField
            End Get
            Set
                Me.mCLastPFRNumberField = value
                Me.RaisePropertyChanged("MCLastPFRNumber")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=12)>  _
        Public Property MCLastPFRAmount() As String
            Get
                Return Me.mCLastPFRAmountField
            End Get
            Set
                Me.mCLastPFRAmountField = value
                Me.RaisePropertyChanged("MCLastPFRAmount")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=13)>  _
        Public Property MCTAVBalance() As String
            Get
                Return Me.mCTAVBalanceField
            End Get
            Set
                Me.mCTAVBalanceField = value
                Me.RaisePropertyChanged("MCTAVBalance")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=14)>  _
        Public Property MCEmployerName() As String
            Get
                Return Me.mCEmployerNameField
            End Get
            Set
                Me.mCEmployerNameField = value
                Me.RaisePropertyChanged("MCEmployerName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=15)>  _
        Public Property MCEmployerBranch() As String
            Get
                Return Me.mCEmployerBranchField
            End Get
            Set
                Me.mCEmployerBranchField = value
                Me.RaisePropertyChanged("MCEmployerBranch")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=16)>  _
        Public Property MCEmployerStatus() As String
            Get
                Return Me.mCEmployerStatusField
            End Get
            Set
                Me.mCEmployerStatusField = value
                Me.RaisePropertyChanged("MCEmployerStatus")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://allcardtech.com.ph/")>  _
    Partial Public Class ACCMCRecordClassResult
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private aCCMCRecordClassField() As MemberContribution
        
        Private isSentField As Boolean
        
        Private errorMessageField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Order:=0)>  _
        Public Property ACCMCRecordClass() As MemberContribution()
            Get
                Return Me.aCCMCRecordClassField
            End Get
            Set
                Me.aCCMCRecordClassField = value
                Me.RaisePropertyChanged("ACCMCRecordClass")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property IsSent() As Boolean
            Get
                Return Me.isSentField
            End Get
            Set
                Me.isSentField = value
                Me.RaisePropertyChanged("IsSent")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property ErrorMessage() As String
            Get
                Return Me.errorMessageField
            End Get
            Set
                Me.errorMessageField = value
                Me.RaisePropertyChanged("ErrorMessage")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://allcardtech.com.ph/")>  _
    Partial Public MustInherit Class MemberInfo
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://allcardtech.com.ph/")>  _
    Partial Public Class HDMFEmploymentHistory
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private extensionDataField As ExtensionDataObject
        
        Private employerNameField As String
        
        Private employerAddressField As String
        
        Private dateEmployedField As String
        
        Private dateSeparatedField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property ExtensionData() As ExtensionDataObject
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
                Me.RaisePropertyChanged("ExtensionData")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property EmployerName() As String
            Get
                Return Me.employerNameField
            End Get
            Set
                Me.employerNameField = value
                Me.RaisePropertyChanged("EmployerName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property EmployerAddress() As String
            Get
                Return Me.employerAddressField
            End Get
            Set
                Me.employerAddressField = value
                Me.RaisePropertyChanged("EmployerAddress")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property DateEmployed() As String
            Get
                Return Me.dateEmployedField
            End Get
            Set
                Me.dateEmployedField = value
                Me.RaisePropertyChanged("DateEmployed")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property DateSeparated() As String
            Get
                Return Me.dateSeparatedField
            End Get
            Set
                Me.dateSeparatedField = value
                Me.RaisePropertyChanged("DateSeparated")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://allcardtech.com.ph/")>  _
    Partial Public Class HDMFBeneficiary
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private extensionDataField As ExtensionDataObject
        
        Private lastnameField As String
        
        Private firstnameField As String
        
        Private middlenameField As String
        
        Private nameExtensionField As String
        
        Private noMiddleNameField As Boolean
        
        Private relationshipField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property ExtensionData() As ExtensionDataObject
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
                Me.RaisePropertyChanged("ExtensionData")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Lastname() As String
            Get
                Return Me.lastnameField
            End Get
            Set
                Me.lastnameField = value
                Me.RaisePropertyChanged("Lastname")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Firstname() As String
            Get
                Return Me.firstnameField
            End Get
            Set
                Me.firstnameField = value
                Me.RaisePropertyChanged("Firstname")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property Middlename() As String
            Get
                Return Me.middlenameField
            End Get
            Set
                Me.middlenameField = value
                Me.RaisePropertyChanged("Middlename")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property NameExtension() As String
            Get
                Return Me.nameExtensionField
            End Get
            Set
                Me.nameExtensionField = value
                Me.RaisePropertyChanged("NameExtension")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property NoMiddleName() As Boolean
            Get
                Return Me.noMiddleNameField
            End Get
            Set
                Me.noMiddleNameField = value
                Me.RaisePropertyChanged("NoMiddleName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property Relationship() As String
            Get
                Return Me.relationshipField
            End Get
            Set
                Me.relationshipField = value
                Me.RaisePropertyChanged("Relationship")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://allcardtech.com.ph/")>  _
    Partial Public Class HDMFContactInfo
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private extensionDataField As ExtensionDataObject
        
        Private country_CodeField As String
        
        Private area_CodeField As String
        
        Private tel_NoField As String
        
        Private local_NoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property ExtensionData() As ExtensionDataObject
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
                Me.RaisePropertyChanged("ExtensionData")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Country_Code() As String
            Get
                Return Me.country_CodeField
            End Get
            Set
                Me.country_CodeField = value
                Me.RaisePropertyChanged("Country_Code")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Area_Code() As String
            Get
                Return Me.area_CodeField
            End Get
            Set
                Me.area_CodeField = value
                Me.RaisePropertyChanged("Area_Code")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property Tel_No() As String
            Get
                Return Me.tel_NoField
            End Get
            Set
                Me.tel_NoField = value
                Me.RaisePropertyChanged("Tel_No")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property Local_No() As String
            Get
                Return Me.local_NoField
            End Get
            Set
                Me.local_NoField = value
                Me.RaisePropertyChanged("Local_No")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://allcardtech.com.ph/")>  _
    Partial Public Class HDMFAddress
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private extensionDataField As ExtensionDataObject
        
        Private hBURNumberField As String
        
        Private buildingField As String
        
        Private lot_NoField As String
        
        Private block_NoField As String
        
        Private phase_NoField As String
        
        Private house_NoField As String
        
        Private streetNameField As String
        
        Private subdivisionField As String
        
        Private baranggayField As String
        
        Private cityMunicipalityField As String
        
        Private provinceField As String
        
        Private regionField As String
        
        Private zIP_CodeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property ExtensionData() As ExtensionDataObject
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
                Me.RaisePropertyChanged("ExtensionData")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property HBURNumber() As String
            Get
                Return Me.hBURNumberField
            End Get
            Set
                Me.hBURNumberField = value
                Me.RaisePropertyChanged("HBURNumber")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Building() As String
            Get
                Return Me.buildingField
            End Get
            Set
                Me.buildingField = value
                Me.RaisePropertyChanged("Building")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property Lot_No() As String
            Get
                Return Me.lot_NoField
            End Get
            Set
                Me.lot_NoField = value
                Me.RaisePropertyChanged("Lot_No")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property Block_No() As String
            Get
                Return Me.block_NoField
            End Get
            Set
                Me.block_NoField = value
                Me.RaisePropertyChanged("Block_No")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property Phase_No() As String
            Get
                Return Me.phase_NoField
            End Get
            Set
                Me.phase_NoField = value
                Me.RaisePropertyChanged("Phase_No")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property House_No() As String
            Get
                Return Me.house_NoField
            End Get
            Set
                Me.house_NoField = value
                Me.RaisePropertyChanged("House_No")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property StreetName() As String
            Get
                Return Me.streetNameField
            End Get
            Set
                Me.streetNameField = value
                Me.RaisePropertyChanged("StreetName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property Subdivision() As String
            Get
                Return Me.subdivisionField
            End Get
            Set
                Me.subdivisionField = value
                Me.RaisePropertyChanged("Subdivision")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property Baranggay() As String
            Get
                Return Me.baranggayField
            End Get
            Set
                Me.baranggayField = value
                Me.RaisePropertyChanged("Baranggay")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property CityMunicipality() As String
            Get
                Return Me.cityMunicipalityField
            End Get
            Set
                Me.cityMunicipalityField = value
                Me.RaisePropertyChanged("CityMunicipality")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=11)>  _
        Public Property Province() As String
            Get
                Return Me.provinceField
            End Get
            Set
                Me.provinceField = value
                Me.RaisePropertyChanged("Province")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=12)>  _
        Public Property Region() As String
            Get
                Return Me.regionField
            End Get
            Set
                Me.regionField = value
                Me.RaisePropertyChanged("Region")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=13)>  _
        Public Property ZIP_Code() As String
            Get
                Return Me.zIP_CodeField
            End Get
            Set
                Me.zIP_CodeField = value
                Me.RaisePropertyChanged("ZIP_Code")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://allcardtech.com.ph/")>  _
    Partial Public Class HDMFMembershipCategory
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private extensionDataField As ExtensionDataObject
        
        Private membershipCategoryField As String
        
        Private employerNameField As String
        
        Private employerAddressField As HDMFAddress
        
        Private employeeIDField As String
        
        Private dateEmployedField As String
        
        Private employmentStatusField As String
        
        Private occupationField As HDMFDescCode
        
        Private aFPSerialBadgeNoField As String
        
        Private depEdDivCodeStnCodeField As String
        
        Private typeOfWorkField As String
        
        Private manningAgencyField As String
        
        Private countryofAssignmentField As String
        
        Private basicSalaryField As String
        
        Private allowanceField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property ExtensionData() As ExtensionDataObject
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
                Me.RaisePropertyChanged("ExtensionData")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property MembershipCategory() As String
            Get
                Return Me.membershipCategoryField
            End Get
            Set
                Me.membershipCategoryField = value
                Me.RaisePropertyChanged("MembershipCategory")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property EmployerName() As String
            Get
                Return Me.employerNameField
            End Get
            Set
                Me.employerNameField = value
                Me.RaisePropertyChanged("EmployerName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property EmployerAddress() As HDMFAddress
            Get
                Return Me.employerAddressField
            End Get
            Set
                Me.employerAddressField = value
                Me.RaisePropertyChanged("EmployerAddress")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property EmployeeID() As String
            Get
                Return Me.employeeIDField
            End Get
            Set
                Me.employeeIDField = value
                Me.RaisePropertyChanged("EmployeeID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property DateEmployed() As String
            Get
                Return Me.dateEmployedField
            End Get
            Set
                Me.dateEmployedField = value
                Me.RaisePropertyChanged("DateEmployed")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property EmploymentStatus() As String
            Get
                Return Me.employmentStatusField
            End Get
            Set
                Me.employmentStatusField = value
                Me.RaisePropertyChanged("EmploymentStatus")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property Occupation() As HDMFDescCode
            Get
                Return Me.occupationField
            End Get
            Set
                Me.occupationField = value
                Me.RaisePropertyChanged("Occupation")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property AFPSerialBadgeNo() As String
            Get
                Return Me.aFPSerialBadgeNoField
            End Get
            Set
                Me.aFPSerialBadgeNoField = value
                Me.RaisePropertyChanged("AFPSerialBadgeNo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property DepEdDivCodeStnCode() As String
            Get
                Return Me.depEdDivCodeStnCodeField
            End Get
            Set
                Me.depEdDivCodeStnCodeField = value
                Me.RaisePropertyChanged("DepEdDivCodeStnCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property TypeOfWork() As String
            Get
                Return Me.typeOfWorkField
            End Get
            Set
                Me.typeOfWorkField = value
                Me.RaisePropertyChanged("TypeOfWork")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=11)>  _
        Public Property ManningAgency() As String
            Get
                Return Me.manningAgencyField
            End Get
            Set
                Me.manningAgencyField = value
                Me.RaisePropertyChanged("ManningAgency")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=12)>  _
        Public Property CountryofAssignment() As String
            Get
                Return Me.countryofAssignmentField
            End Get
            Set
                Me.countryofAssignmentField = value
                Me.RaisePropertyChanged("CountryofAssignment")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=13)>  _
        Public Property BasicSalary() As String
            Get
                Return Me.basicSalaryField
            End Get
            Set
                Me.basicSalaryField = value
                Me.RaisePropertyChanged("BasicSalary")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=14)>  _
        Public Property Allowance() As String
            Get
                Return Me.allowanceField
            End Get
            Set
                Me.allowanceField = value
                Me.RaisePropertyChanged("Allowance")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://allcardtech.com.ph/")>  _
    Partial Public Class HDMFDescCode
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private extensionDataField As ExtensionDataObject
        
        Private descriptionField As String
        
        Private codeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property ExtensionData() As ExtensionDataObject
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
                Me.RaisePropertyChanged("ExtensionData")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
                Me.RaisePropertyChanged("Description")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Code() As String
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
                Me.RaisePropertyChanged("Code")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://allcardtech.com.ph/")>  _
    Partial Public Class HDMFName
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private extensionDataField As ExtensionDataObject
        
        Private lastNameField As String
        
        Private firstNameField As String
        
        Private middleNameField As String
        
        Private nameExtensionField As String
        
        Private noMiddleNameField As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property ExtensionData() As ExtensionDataObject
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
                Me.RaisePropertyChanged("ExtensionData")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property LastName() As String
            Get
                Return Me.lastNameField
            End Get
            Set
                Me.lastNameField = value
                Me.RaisePropertyChanged("LastName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property FirstName() As String
            Get
                Return Me.firstNameField
            End Get
            Set
                Me.firstNameField = value
                Me.RaisePropertyChanged("FirstName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property MiddleName() As String
            Get
                Return Me.middleNameField
            End Get
            Set
                Me.middleNameField = value
                Me.RaisePropertyChanged("MiddleName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property NameExtension() As String
            Get
                Return Me.nameExtensionField
            End Get
            Set
                Me.nameExtensionField = value
                Me.RaisePropertyChanged("NameExtension")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property NoMiddleName() As Boolean
            Get
                Return Me.noMiddleNameField
            End Get
            Set
                Me.noMiddleNameField = value
                Me.RaisePropertyChanged("NoMiddleName")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://allcardtech.com.ph/")>  _
    Partial Public Class HDMFMember
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private extensionDataField As ExtensionDataObject
        
        Private pagIBIGIDNoField As String
        
        Private rTNField As String
        
        Private memberNameField As HDMFName
        
        Private birthCertNameField As HDMFName
        
        Private motherNameField As HDMFName
        
        Private fatherNameField As HDMFName
        
        Private spouseNameField As HDMFName
        
        Private dateOfBirthField As String
        
        Private placeOfBirthField As String
        
        Private countryOfBirthField As String
        
        Private cityMunicipalityOfBirthField As String
        
        Private genderField As String
        
        Private civilStatusField As String
        
        Private citizenshipField As HDMFDescCode
        
        Private prominentDistinguishingFacialFeatureField As String
        
        Private emailAddressField As String
        
        Private commonRefNoField As String
        
        Private sSSIDNoField As String
        
        Private gSISIDNoField As String
        
        Private tINField As String
        
        Private memberCategoryInfoField As HDMFMembershipCategory
        
        Private permanentAddressField As HDMFAddress
        
        Private presentAddressField As HDMFAddress
        
        Private preferredMailingAddressField As String
        
        Private homeTelNoField As HDMFContactInfo
        
        Private mobileTelNoField As HDMFContactInfo
        
        Private businessDirectTelNoField As HDMFContactInfo
        
        Private businessTrunkTelNoField As HDMFContactInfo
        
        Private beneficiariesField() As HDMFBeneficiary
        
        Private employmentHistoryField() As HDMFEmploymentHistory
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property ExtensionData() As ExtensionDataObject
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
                Me.RaisePropertyChanged("ExtensionData")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property PagIBIGIDNo() As String
            Get
                Return Me.pagIBIGIDNoField
            End Get
            Set
                Me.pagIBIGIDNoField = value
                Me.RaisePropertyChanged("PagIBIGIDNo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property RTN() As String
            Get
                Return Me.rTNField
            End Get
            Set
                Me.rTNField = value
                Me.RaisePropertyChanged("RTN")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property MemberName() As HDMFName
            Get
                Return Me.memberNameField
            End Get
            Set
                Me.memberNameField = value
                Me.RaisePropertyChanged("MemberName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property BirthCertName() As HDMFName
            Get
                Return Me.birthCertNameField
            End Get
            Set
                Me.birthCertNameField = value
                Me.RaisePropertyChanged("BirthCertName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property MotherName() As HDMFName
            Get
                Return Me.motherNameField
            End Get
            Set
                Me.motherNameField = value
                Me.RaisePropertyChanged("MotherName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property FatherName() As HDMFName
            Get
                Return Me.fatherNameField
            End Get
            Set
                Me.fatherNameField = value
                Me.RaisePropertyChanged("FatherName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property SpouseName() As HDMFName
            Get
                Return Me.spouseNameField
            End Get
            Set
                Me.spouseNameField = value
                Me.RaisePropertyChanged("SpouseName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property DateOfBirth() As String
            Get
                Return Me.dateOfBirthField
            End Get
            Set
                Me.dateOfBirthField = value
                Me.RaisePropertyChanged("DateOfBirth")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property PlaceOfBirth() As String
            Get
                Return Me.placeOfBirthField
            End Get
            Set
                Me.placeOfBirthField = value
                Me.RaisePropertyChanged("PlaceOfBirth")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property CountryOfBirth() As String
            Get
                Return Me.countryOfBirthField
            End Get
            Set
                Me.countryOfBirthField = value
                Me.RaisePropertyChanged("CountryOfBirth")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=11)>  _
        Public Property CityMunicipalityOfBirth() As String
            Get
                Return Me.cityMunicipalityOfBirthField
            End Get
            Set
                Me.cityMunicipalityOfBirthField = value
                Me.RaisePropertyChanged("CityMunicipalityOfBirth")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=12)>  _
        Public Property Gender() As String
            Get
                Return Me.genderField
            End Get
            Set
                Me.genderField = value
                Me.RaisePropertyChanged("Gender")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=13)>  _
        Public Property CivilStatus() As String
            Get
                Return Me.civilStatusField
            End Get
            Set
                Me.civilStatusField = value
                Me.RaisePropertyChanged("CivilStatus")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=14)>  _
        Public Property Citizenship() As HDMFDescCode
            Get
                Return Me.citizenshipField
            End Get
            Set
                Me.citizenshipField = value
                Me.RaisePropertyChanged("Citizenship")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=15)>  _
        Public Property ProminentDistinguishingFacialFeature() As String
            Get
                Return Me.prominentDistinguishingFacialFeatureField
            End Get
            Set
                Me.prominentDistinguishingFacialFeatureField = value
                Me.RaisePropertyChanged("ProminentDistinguishingFacialFeature")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=16)>  _
        Public Property EmailAddress() As String
            Get
                Return Me.emailAddressField
            End Get
            Set
                Me.emailAddressField = value
                Me.RaisePropertyChanged("EmailAddress")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=17)>  _
        Public Property CommonRefNo() As String
            Get
                Return Me.commonRefNoField
            End Get
            Set
                Me.commonRefNoField = value
                Me.RaisePropertyChanged("CommonRefNo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=18)>  _
        Public Property SSSIDNo() As String
            Get
                Return Me.sSSIDNoField
            End Get
            Set
                Me.sSSIDNoField = value
                Me.RaisePropertyChanged("SSSIDNo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=19)>  _
        Public Property GSISIDNo() As String
            Get
                Return Me.gSISIDNoField
            End Get
            Set
                Me.gSISIDNoField = value
                Me.RaisePropertyChanged("GSISIDNo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=20)>  _
        Public Property TIN() As String
            Get
                Return Me.tINField
            End Get
            Set
                Me.tINField = value
                Me.RaisePropertyChanged("TIN")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=21)>  _
        Public Property MemberCategoryInfo() As HDMFMembershipCategory
            Get
                Return Me.memberCategoryInfoField
            End Get
            Set
                Me.memberCategoryInfoField = value
                Me.RaisePropertyChanged("MemberCategoryInfo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=22)>  _
        Public Property PermanentAddress() As HDMFAddress
            Get
                Return Me.permanentAddressField
            End Get
            Set
                Me.permanentAddressField = value
                Me.RaisePropertyChanged("PermanentAddress")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=23)>  _
        Public Property PresentAddress() As HDMFAddress
            Get
                Return Me.presentAddressField
            End Get
            Set
                Me.presentAddressField = value
                Me.RaisePropertyChanged("PresentAddress")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=24)>  _
        Public Property PreferredMailingAddress() As String
            Get
                Return Me.preferredMailingAddressField
            End Get
            Set
                Me.preferredMailingAddressField = value
                Me.RaisePropertyChanged("PreferredMailingAddress")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=25)>  _
        Public Property HomeTelNo() As HDMFContactInfo
            Get
                Return Me.homeTelNoField
            End Get
            Set
                Me.homeTelNoField = value
                Me.RaisePropertyChanged("HomeTelNo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=26)>  _
        Public Property MobileTelNo() As HDMFContactInfo
            Get
                Return Me.mobileTelNoField
            End Get
            Set
                Me.mobileTelNoField = value
                Me.RaisePropertyChanged("MobileTelNo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=27)>  _
        Public Property BusinessDirectTelNo() As HDMFContactInfo
            Get
                Return Me.businessDirectTelNoField
            End Get
            Set
                Me.businessDirectTelNoField = value
                Me.RaisePropertyChanged("BusinessDirectTelNo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=28)>  _
        Public Property BusinessTrunkTelNo() As HDMFContactInfo
            Get
                Return Me.businessTrunkTelNoField
            End Get
            Set
                Me.businessTrunkTelNoField = value
                Me.RaisePropertyChanged("BusinessTrunkTelNo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Order:=29)>  _
        Public Property Beneficiaries() As HDMFBeneficiary()
            Get
                Return Me.beneficiariesField
            End Get
            Set
                Me.beneficiariesField = value
                Me.RaisePropertyChanged("Beneficiaries")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Order:=30)>  _
        Public Property EmploymentHistory() As HDMFEmploymentHistory()
            Get
                Return Me.employmentHistoryField
            End Get
            Set
                Me.employmentHistoryField = value
                Me.RaisePropertyChanged("EmploymentHistory")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface PagIbig_WSSoapChannel
        Inherits MiddleServer.PagIbig_WSSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class PagIbig_WSSoapClient
        Inherits System.ServiceModel.ClientBase(Of MiddleServer.PagIbig_WSSoap)
        Implements MiddleServer.PagIbig_WSSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function is_MID_RTN_Exist(ByVal MID_RTN As String, ByVal webuser As String, ByVal webpass As String) As MiddleServer.SubmitResult Implements MiddleServer.PagIbig_WSSoap.is_MID_RTN_Exist
            Return MyBase.Channel.is_MID_RTN_Exist(MID_RTN, webuser, webpass)
        End Function
        
        Public Function Is_Member_Active(ByVal UID As String, ByVal LN As String, ByVal FN As String, ByVal MN As String) As MiddleServer.ACCMCRecordClassResult Implements MiddleServer.PagIbig_WSSoap.Is_Member_Active
            Return MyBase.Channel.Is_Member_Active(UID, LN, FN, MN)
        End Function
        
        Public Function is_MemberFullName_Exist(ByVal LName As String, ByVal MName As String, ByVal FName As String, ByVal DOB As Date) As MiddleServer.PrimaryMultiple Implements MiddleServer.PagIbig_WSSoap.is_MemberFullName_Exist
            Return MyBase.Channel.is_MemberFullName_Exist(LName, MName, FName, DOB)
        End Function
        
        Public Function updateRTN(ByVal MID As String) As MiddleServer.Result_GetMemberID Implements MiddleServer.PagIbig_WSSoap.updateRTN
            Return MyBase.Channel.updateRTN(MID)
        End Function
        
        Public Function PagIBIGLogIN(ByVal ApprovedID As String, ByVal ApprovedPW As String, ByVal MID As String) As MiddleServer.Result_AuthenticateMCIFApprover Implements MiddleServer.PagIbig_WSSoap.PagIBIGLogIN
            Return MyBase.Channel.PagIBIGLogIN(ApprovedID, ApprovedPW, MID)
        End Function
    End Class
End Namespace
